### ISSUE TITLE
Cannot find module './lib/React'

### ISSUE THREAD

**Issue by doodiosie** [gadicc/meteor-blaze-react-component#10]
When I install the package on my project and try to run it, without importing it into anywhere I get this error:
Error: Cannot find module './lib/React'
If i remove the package then it all works fine but adding it again brings back the error

**Comment by gadicc** [comment]
Sorry for the 2.5 yr delay :weary:   Closing as probably no longer relevant, however if it is, please let me know and I'll give it my full attention.  Apologies.
