### ISSUE TITLE
Render blaze templates in a SSR react layout?

### ISSUE THREAD

**Issue by j-jackson** [gadicc/meteor-blaze-react-component#11]
[I understand](https://github.com/gadicc/meteor-blaze-react-component/issues/1) that we can't render blaze templates server side, but I was wondering if we can render them in a server side rendered react layout?

My goal is to render the layout on the server with react & react-helmet and then just loop over my blaze templates in the main section.

i.e

```javascript
import React from 'react';
import Helmet from 'react-helmet';
import Blaze from 'meteor/gadicc:blaze-react-component';

const App = () => (
  <div>
    <Helmet title="My Site!" />
    <Blaze template="sectionList" sections={sections} />
  </div>
);
```

Then something like

```javascript
<template name="sectionList">
  <h2>My Site</h2>

  {{#each section in sections}}
    {{> Template.dynamic template=template}}
  {{/each}}

</template>
```

The end result would be a fast SSR layout with helmet and client side rendered blaze templates that I could start to convert over to react.

**Comment by gadicc** [comment]
Hey, unfortunately it's the same issue :(  We still have to render with Blaze before we can pass it to React.  I'm a bit out of touch but see what's happening with the Blaze project now that it's community run; SSR was being seriously looked into last time I checked.

**Comment by j-jackson** [comment]
Thanks Gadi. I asked over in the Blaze repo and Mitar said that its mostly done but know one is working on it.
