### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by gordal18** [gadicc/meteor-blaze-react-component#15]
Hello, there
Thank you for opportunity.
I am newbie on Meteor.
I need your help now.
Actually, I searched your github carefully.
I tried to use blaze in react component.

import Blaze from 'meteor/gadicc:blaze-react-component';
import { Template } from 'meteor/templating';
import RealBlaze from 'meteor/blaze';
import { Tracker } from 'meteor/tracker';

...
render(){
return (<Blaze template="calendar" />);
}

The Files calendar.html and calendar.js are in the same folder.
At that time, I can see this kind of issue

blaze-react-component-client.js:27 Uncaught Error: No Template["calendar"] exists.  If this template originates in your app, make sure you have the `templating` package installed (and not, for e.g. `static-html`)

I hope to solve this problem ASAP.
Because I have urgent task now.
Best Regards,

Kakha

**Comment by gadicc** [comment]
Hey @gordal18.  Can you check in your `.meteor/packages` file and confirm that:

1. `templating` is there
1. `static-html` is not there

(assuming that's ok for your project)

**Comment by gordal18** [comment]
templating  is not here
and static-html is here.

**Comment by gadicc** [comment]
Ok, so you need to `meteor remove static-html` and `meteor add templating`, assuming that doesn't have any implications for your project (it's fine unless you know it isn't :)).

**Comment by gordal18** [comment]
Hello, there
I confirmed it
but same issue...

**Comment by gordal18** [comment]
If possible, can you help me with teamviewer?

**Comment by gadicc** [comment]
Hi @gordal18, I regret that I won't have time to help with teamviewer.  Maybe someone on the Meteor forums can help?  If you still have no luck, if you can share your project with me on github, I'll take a look when I have a chance.

**Comment by gadicc** [comment]
This was probably #20.
