### ISSUE TITLE
Uncaught Error: Target container is not a DOM element.

### ISSUE THREAD

**Issue by bryanpleblanc** [gadicc/meteor-blaze-react-component#17]
I just did the Meteor React ToDo's tutorial and as a test I'm trying to insert a Blaze Template into react. 

Keep getting 'Target container is not a DOM element.' on the client side

**Meteor Packages:**
meteor-base@1.4.0
mobile-experience@1.0.5
mongo@1.5.0
tracker@1.2.0
standard-minifier-js@2.3.4
reactive-var
es5-shim@4.8.0
ecmascript@0.11.1
shell-server@0.3.1
react-meteor-data
accounts-base
accounts-password
accounts-ui
momentjs:moment
fourseven:scss
seba:minifiers-autoprefixer
kendo-ui-pro
bootstrap4
underscore
gadicc:blaze-react-component
templating

Adding Blaze to React component 
![capture1](https://user-images.githubusercontent.com/25310829/43173235-a60d042a-8f68-11e8-8661-72b89e844c30.PNG)

Using react router to render the component
![capture 4](https://user-images.githubusercontent.com/25310829/43174137-5281e802-8f6d-11e8-8b27-5d7e445dbd77.PNG)

React router setup
![capture 5](https://user-images.githubusercontent.com/25310829/43174222-c3cfb282-8f6d-11e8-9982-c7835481b3a7.PNG)

Package.json
![capture2](https://user-images.githubusercontent.com/25310829/43173940-65b38a76-8f6c-11e8-99cb-4c16710786c9.PNG)

**Comment by gadicc** [comment]
hi @bryanpleblanc 

did everything work before adding this package?

can you give the full stack trace of the error?

might be easier if you put the whole project on github somewhere for me to take a proper look.

**Comment by bryanpleblanc** [comment]
If I remove the <Blaze> tag and add back the 'static-html' meteor package then everything works. If I add the 'static-html' package back then I get a different error. But based on your documentation 'static-html' shouldn't be added.  I went ahead and added this project to github. Its in repository Meteor-react-todos.

**Comment by gadicc** [comment]
hey @bryanpleblanc 

According to https://docs.meteor.com/api/core.html:

> On a client, startup callbacks from packages will be called first, followed by <body> templates from your .html files, followed by your application code.

So, this error is because when `render()` is called, `<div id="render-target" />` doesn't exist yet.

I would have expected the "correct" way to do this would be to use the template rendered event:

```
Template.body.onRendered(() => {
  render(renderRoutes(), document.getElementById('render-target'));
});
```

but this doesn't seem to work either.  **However, an easy fix seems to just be to import the `html` file before calling Meteor.startup**:

```js
import ....
import './main.html';

Meteor.startup(...);
```

I don't feel this is intuitive or obvious but I write my findings here in the hope it will help others.  It seems a lot of work has happened in Meteor and Blaze since I last used them.

Good luck!

**Comment by gadicc** [comment]
Note, there is nothing specific about this issue to this package, you'd get the same error even without this package when switching out `templating` for `static-html`.  Then again, probably many (most?) people using React with `templating` might also be using this package, so maybe we should warn about it.  In short:

> PLEASE IF ANYONE ELSE HAS EXPERIENCE THIS ISSUE LET ME KNOW 

and I'll add it to the README :)
