### ISSUE TITLE
Support BlazeComponents?

### ISSUE THREAD

**Issue by thebarty** [gadicc/meteor-blaze-react-component#18]
Hi guys,

this does NOT work with BlazeComponents.

Would it be an easy thing for you to support it? See https://github.com/peerlibrary/meteor-blaze-components/issues/154

**Comment by duce3** [comment]
I ran into this as well and submitted a pull request that supports this.

**Comment by gadicc** [comment]
Legend, thanks, @duce3! Merged and published as v1.4.2. Thanks for your contribution!
