### ISSUE TITLE
Uncaught Error: No Template["abc"] exists with "templating" installed 

### ISSUE THREAD

**Issue by krishaamer** [gadicc/meteor-blaze-react-component#20]
Hi @gadicc, thanks for an awesome idea for a package!

I'm trying to use some blaze templates in React, removed "static-html" and added "templating", followed the docs to the letter however it seems the component can't see my Blaze templates. 

Should the templates be in the client folder and automatically included or do I still need to import them somehow?

Using Meteor 1.8.2-beta.15

Thanks,
Kris from Estonia

**Comment by gadicc** [comment]
Hey @krishaamer

To be honest I haven't used this package in a realllly long time, but, from what I recall, templates in the `client` folder aren't automatically imported, and you should import them manually.  Can you try e.g. the following and see if it makes the template available?

```js
// no need to name the import, we're just instructing Meteor to load it
import './myTemplate.html';
```

Let me know either way and I'll add this to the docs for clarity.  Also, you could do this in any `.js` file that makes sense (e.g. a single `templates.js` to load all your templates).  If you want some more information, I see I actually wrote about importing templates (unrelated to this package) in the forum a few years back, https://forums.meteor.com/t/what-is-import-of-html-file/20431.

**Comment by gadicc** [comment]
@krishaamer, added this to the README, let me know if you still have issues.
