### ISSUE TITLE
Uncaught ReferenceError: Template is not defined

### ISSUE THREAD

**Issue by acomito** [gadicc/meteor-blaze-react-component#5]
I'm having some trouble. The package seems to not have access to meteor's Template?

`blaze-react-component-client.js:12     Uncaught ReferenceError: Template is not defined`

**Comment by gadicc** [comment]
Thanks for the report!  Can you confirm if the just-published `v1.1.2` fixes the issue for you?

**Comment by acomito** [comment]
Hey sorry I forgot to update! I had static-html package when I needed the blaze templating package.

Now it works like a charm. Sorry for the false alarm.

**Comment by gadicc** [comment]
Ah ok thanks for reporting back.  I think I should add this to the docs and even have the package warn if it detects this case.

**Comment by acomito** [comment]
It can't hurt to add if you have the time.

**Comment by gadicc** [comment]
Done in v1.2.0 (https://github.com/gadicc/meteor-blaze-react-component/tree/1a4768de7f00c536007f7c085bb53872396dbf2d), which now also allows passing templates directly without using the Template global.  Thanks for the update.
